### ISSUE TITLE
YAML e modelagem

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/pwc#4]
Fluxo padrão:
- CAERN + comprovante
- COSERN + comprovante
- Recibo de salário
- Recibo de salário "cópia"
- Guia de pagamento + comprovante
- Folha de ponto girada
- Recibo de vale-transporte
- NET + comprovante

Fluxo de exceção:
- Recibo de 13º salário, 1ª parcela
- Recibo de 13º salário, 2ª parcela

---

Fluxo de exceção 2 (a conhecer):
- Recibo de vale-transporte por rubrica do eSocial

Fluxo de exceção 3 (a conhecer):
- Controle de horas extras?

**Comment by alexandre-mbm** [comment]
```yaml
- CAERN de Joana:
  - relatorio.pdf
  - caern.png
- COSERN de Joana:
  - [2a Via de Fatura.pdf, 1]
  - cosern.png
- Recibo de salário (Benedita):
  - [eSocial_Demonstrativo_Recibo_Novembro_2016.pdf, 1, stamp: 23,45]
  - null
  - enabled: true
- Recibo de 13º, parcela 1 (Benedita):
  - [eSocial_Demonstrativo_Recibo_Novembro_2016.pdf, 2, stamp: 43,35]
  - null
  - enabled: false
- Guia do eSocial (Benedita):
  - GuiaPagamento_14326485515_281120160220407802.pdf
  - Comprovante.pdf
- Folha de ponto (Benedita):
  - [fl.pt.dez.pdf, 1-2, landscape]
- Recibo de vales-transporte (Benedita):
  - rec.vt.dez.pdf
  - null
- Pagamento da NET:
  - [Fatura Net.pdf, 1]
  - NET.png
```
